### ISSUE TITLE
Cannot set property 'content-length' of undefined

### ISSUE THREAD

**Issue by JamshedLatipov** [unRob/sip-client#7]
when i call message.send(); application crash with following error

/home/jamshed/Documents/work/sipPhone/node_modules/sip/sip.js:361
  m.headers['content-length'] = (m.content || '').length;

```
var SIPClient = require('sip-client');
var util = require('util');

// I suppose these are pretty self explanatory
var opts = {
	user: '1000',
	password: '1000',
	host: '192.168.226.6',
	debug: true //unless you want to see HARDCORE SIP ACTION!
};

var client = new SIPClient(opts);

var uri = {
	schema: 'sip',
	host: opts.host,
	user: opts.user
};
var headers = {
	contact: "<sip:"+opts.host+":5060>",
	from: {
		name: 'A SIP User',
		uri: uri
	},
	to: {
		name: 'A SIP User',
		uri: uri
	}
};

var message = client.message('register', {host: opts.host}, headers);
message.send();
```

Please help me!

**Comment by unRob** [comment]
Sorry Jamshed, without the full stacktrace, error message, and your version of node it'd be really hard for me to help you debug. Also, I'm very sorry about the sad state of this codebase, which hasn't been maintained in over 4 years. Because of that I'm not familiar enough to be helpful in these situations.

I'd recommend you try looking at the file where the error occurred (line 361 of `/home/jamshed/Documents/work/sipPhone/node_modules/sip/sip.js`) and start tracing back the value of `m` to see what happened and possibly get an idea on how to fix it. Good luck!
